version: '3.4'

services:
  web:
    build:
      context: .
    container_name: php8.2-mag2.4.6-apache_magento
    environment:
      - MAGENTO_HOST=http://localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=magento
      - MAGENTO_USERNAME=user
      - MAGENTO_PASSWORD=user123
      - MAGENTO_EMAIL=transbankdevelopers@continuum.cl
      - MAGENTO_FIRST_NAME=Tbk
      - MAGENTO_LAST_NAME=Transbank
    command:
      - /bin/sh
      - -c
      - |
        sleep 15
        ./magento_install.sh
        run
    ports:
      - "80:80"
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.2
    container_name: php8.2-mag2.4.6-apache_mariadb
    ports:
      - "33006:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: php8.2-mag2.4.6-apache_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - name=elasticsearch
      - discovery.type=single-node




