language: php
php:
  - '7.1'
script: echo "We don't have tests yet :("
before_deploy:
  - sh package.sh
deploy:
  - provider: releases
    name: "$TRAVIS_TAG"
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file: "transbank-plugin-magento2-webpay-rest.zip"
    on:
      repo: TransbankDevelopers/transbank-plugin-magento2-webpay-rest
      tags: true
      php: 7.1
