#!/usr/bin/env bash

DIR='./plugin/Transbank/Webpay'
mkdir -p $DIR
cp -rf ../Block $DIR
cp -rf ../Controller $DIR
cp -rf ../etc $DIR
cp -rf ../Model $DIR
cp -rf ../view $DIR
cp -rf ../composer.json $DIR
cp -rf ../registration.php $DIR
cp -rf ../Setup $DIR
