
<a class ="tbk_btn tbk_danger_btn" data-toggle="modal" id="tbk_button_modal" onclick="showModal()" class="informationButton">Información</a>

<div id="popup-modal" style="display:none">
    <div id="tbk_tabs_menu">
        <ul class="nav nav-tabs">
        <li class="active"> <a data-toggle="tab" href="#modal_info" class="tbk_tabs">Información</a></li>
        <li> <a data-toggle="tab" href="#modal_php_info" class="tbk_tabs">PHP info</a></li>
        <li> <a data-toggle="tab" href="#modal_logs" class="tbk_tabs">Registros</a></li>
        </ul>
    </div>
    <div class="modal-body">
        <div class="tab-content">
            <div id="modal_info" class="tab-pane in active">

                <h3 class="tbk_title_h3">Informe pdf</h3>
                <a class="tbk_btn tbk_danger_btn" href='<?php echo $this->tbk_data['url_create_pdf_report']; ?>' target="_blank">
                    Crear PDF
                </a>

                <h3 class="tbk_title_h3">Información de Plugin / Ambiente</h3>
                <table class="tbk_table_info">
                    <tr>
                        <td><div title="Nombre del E-commerce instalado en el servidor" class="label label-info">?</div> <strong>Software E-commerce: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['ecommerce']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Versión de <?php echo $this->tbk_data['ecommerce']; ?> instalada en el servidor" class="label label-info">?</div> <strong>Version E-commerce: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['ecommerce_version']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Versión del plugin Webpay para <?php echo $this->tbk_data['ecommerce']; ?> instalada actualmente" class="label label-info">?</div> <strong>Versión actual del plugin: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['current_plugin_version']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Última versión del plugin Webpay para <?php echo $this->tbk_data['ecommerce']; ?> disponible" class="label label-info">?</div> <strong>Última versión del plugin: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['last_plugin_version']; ?></td>
                    </tr>
                </table>

                <br>

                <h3 class="tbk_title_h3">Validación certificados</h3>
                <h4 class="tbk_table_title">Consistencias</h4>
                <table class="tbk_table_info">
                    <tr>
                        <td><div title="Informa si las llaves ingresadas por el usuario corresponden al certificado entregado por Transbank" class="label label-info">?</div> <strong>Consistencias con llaves: </strong></td>
                        <td class="tbk_table_td"><span class=<?php
                        if($this->tbk_data['cert_vs_private'] == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-danger2">';}
                        echo $this->tbk_data['cert_vs_private'];
                        ?>
                        </span></td>
                    </tr>
                    <tr>
                        <td><div title="Informa si el código de comercio ingresado por el usuario corresponde al certificado entregado por Transbank" class="label label-info">?</div> <strong>Validación Código de comercio: </strong></td>
                        <td class="tbk_table_td"><span class= <?php
                        if($this->tbk_data['commerce_code_validate'] == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-danger2">';}
                        echo $this->tbk_data['commerce_code_validate'];
                        ?></span></td>
                    </tr>
                </table>

                <hr>

                <h4 class="tbk_table_title">Información del certificado</h4>
                <table class="tbk_table_info">
                    <tr>
                        <td><div title="CN (common name) dentro del certificado, en este caso corresponde al código de comercio emitido por Transbank" class="label label-info">?</div> <strong>Código de Comercio Válido: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['subject_commerce_code']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Versión del certificado emitido por Transbank" class="label label-info">?</div> <strong>Versión cetificado: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['cert_version']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Informa si el certificado está vigente actualmente" class="label label-info">?</div> <strong>Vigencia: </strong></td>
                        <td class="tbk_table_td"><span  class= <?php
                        if($this->tbk_data['cert_is_valid']  == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-danger2">';}
                        echo  $this->tbk_data['cert_is_valid'];
                        ?></span></td>
                    </tr>
                    <tr>
                        <td><div title="Fecha desde la cual el certificado es válido" class="label label-info">?</div> <strong>Válido desde: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['valid_from']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Fecha hasta la cual el certificado es válido" class="label label-info">?</div> <strong>Válido hasta: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['valid_to']; ?></td>
                    </tr>
                </table>

                <br>

                <h3 class="tbk_title_h3">Estado de la Extensiones de PHP</h3>
                <h4 class="tbk_table_title">Información Principal</h4>
                <table class="tbk_table_info">
                    <tr>
                        <td><div title="Descripción del Servidor Web instalado" class="label label-info">?</div> <strong>Software Servidor: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['server_version']; ?></td>
                    </tr>
                    </table>
                    <hr>
                    <h4 class="tbk_table_title">PHP</h4>
                    <table class="tbk_table_info">
                    <tr>
                        <td><div title="Informa si la versión de PHP instalada en el servidor es compatible con el plugin de Webpay" class="label label-info">?</div> <strong>Estado de PHP</strong></td>
                        <td class="tbk_table_td"><span class= <?php
                        if($this->tbk_data['php_status']  == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-warning">';}
                        echo  $this->tbk_data['php_status'];
                        ?></span></td>
                    </tr>
                    <tr>
                        <td><div title="Versión de PHP instalada en el servidor" class="label label-info">?</div> <strong>Versión: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['php_version']; ?></td>
                    </tr>
                </table>

                <hr>

                <h4 class="tbk_table_title">Extensiones PHP requeridas</h4>
                <table class="table table-responsive table-striped">
                    <tr>
                        <th>Extensión</th>
                        <th>Estado</th>
                        <th class="tbk_table_td">Versión</th>
                    </tr>
                    <tr>
                        <td style="font-weight:bold">openssl</td>
                        <td class="tbk_table_td"><span class= <?php
                        if( $this->tbk_data['openssl_status']  == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-danger2">';}
                        echo   $this->tbk_data['openssl_status'];
                        ?></span></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['openssl_version']; ?></td>
                    </tr>
                    <tr>
                        <td style="font-weight:bold">SimpleXml</td>
                        <td class="tbk_table_td"><span class= <?php
                        if( $this->tbk_data['SimpleXML_status']  == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-danger2">';}
                        echo $this->tbk_data['SimpleXML_status'];
                        ?></span></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['SimpleXML_version']; ?></td>
                    </tr>
                    <tr>
                        <td style="font-weight:bold">soap</td>
                        <td class="tbk_table_td"><span class= <?php
                        if( $this->tbk_data['soap_status']  == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-danger2">';}
                        echo $this->tbk_data['soap_status'];
                        ?></span></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['soap_version']; ?></td>
                    </tr>
                    <tr>
                        <td style="font-weight:bold">dom</td>
                        <td class="tbk_table_td"><span class= <?php
                        if( $this->tbk_data['dom_status']  == 'OK'){
                            echo '"label label-success2">';}
                        else{
                            echo '"label label-danger2">';}
                        echo $this->tbk_data['dom_status'];
                        ?></span></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['dom_version']; ?></td>
                    </tr>
                </table>

                <br>

                <h3 class="tbk_title_h3">Validación Transacción</h3>
                <h4 class="tbk_table_title">General</h4>
                <table class="tbk_table_info">
                    <tr>
                        <td class="tbk_table_td"> <button type="button" class="check_conn btn btn-sm btn-primary">Verificar Conexión</button>  </td>
                    </tr>
                </table>

                <hr>

                <h4 class="tbk_table_title">Respuesta</h4>
                <table class="tbk_table_info">
                    <tr id="row_response_status" style="display:none">
                        <td><div title="Informa el estado de la comunicación con Transbank mediante método init_transaction" class="label label-info">?</div> <strong>Estado: </strong></td>
                        <td><span class="status-label label" style="display:none"></span></td>
                        </tr>
                        <tr id="row_response_url" style="display:none">
                            <td><div title="URL entregada por Transbank para realizar la transacción" class="label label-info">?</div> <strong>URL: </strong></td>
                            <td class="tbk_table_trans content_url"></td>
                        </tr>
                        <tr id="row_response_token" style="display:none">
                            <td><div title="Token entregada por Transbank para realizar la transacción" class="label label-info">?</div> <strong>Token</strong></td>
                            <td class="tbk_table_trans content_token"></td>
                        </tr>
                        <tr id="row_error_message" style="display:none">
                            <td><div title="Mensaje de error devuelto por Transbank al fallar init_transaction" class="label label-info">?</div> <strong>Error</strong></td>
                            <td class="tbk_table_trans error_content"></td>
                        </tr>
                        <tr id="row_error_detail" style="display:none">
                            <td><div title="Detalle del error devuelto por Transbank al fallar init_transaction" class="label label-info">?</div> <strong>Detalle: </strong></td>
                        <td class="tbk_table_trans error_detail_content"></td>
                    </tr>
                </table>
            <br>
        </div>

        <div id="modal_php_info" class="tab-pane">
            <h3 class="tbk_title_h3">Informe PHP info</h3>
            <a class="tbk_btn tbk_danger_btn" href='<?php echo $this->tbk_data['url_create_pdf_php_info']; ?>' target="_blank">
                Crear PHP info
            </a>
            <fieldset>
                <h3 class="tbk_title_h3">PHP info</h3>
                <span style="font-size: 10px; font-family:monospace; display: block; background: white;overflow: hidden; width: 90%;" >
                    <?php echo $this->tbk_data['php_info']; ?>
                </span>
            </fieldset>
        </div>

        <div id="modal_logs" class="tab-pane">
            <fieldset>
                <h3 class="tbk_title_h3" style="display: none !important;">Configuración</h3>
                <table class="tbk_table_info" style="display: none !important;">
                    <tr>
                        <td><div title="Al activar esta opción se habilita que se guarden los datos de cada compra mediante Webpay" class="label label-info">?</div> <strong>Activar Registro: </strong></td>
                        <td class="tbk_table_td">
                        <?php
                            if ($this->tbk_data['lockfile']){
                                echo '<input type="checkbox" id="action_check" name="action_check" checked data-size="small" value="activate">';
                            } else {
                                echo '<input type="checkbox" id="action_check" name="action_check" data-size="small" state="false">';
                            }
                        ?>
                        </td>
                    </tr>
                </table>

                <table class="tbk_table_info" style="display: none !important;">
                    <tr>
                        <td><div title="Cantidad de días que se conservan los datos de cada compra mediante Webpay" class="label label-info">?</div> <strong>Cantidad de Días a Registrar: </strong></td>
                        <td class="tbk_table_td"><input id="days" name="days" type="number" min="1" max="30" value="<?php echo $this->tbk_data['log_days']?>"> días</td>
                    </tr>
                    <tr>
                        <td><div title="Peso máximo (en Megabytes) de cada archivo que guarda los datos de las compras mediante Webpay" class="label label-info">?</div> <strong>Peso máximo de Registros:  </strong></td>
                        <td class="tbk_table_td"><select style="width: 100px; display: initial;" id="size" name="size">
                        <?php
                            for ($c=1;$c<10;$c++){
                            echo '<option value="'.$c.'"';
                            if ($c == $this->tbk_data['log_size'])
                                echo 'selected';
                            echo '>'.$c.'</option>';
                            }
                        ?>
                        </select> Mb</td>
                    </tr>
                </table>

                <br>
                <a id="btn-save-data-conf" class="tbk_btn tbk_danger_btn" href="javascript:void();" style="display: none !important;">
                Actualizar Parametros
                </a>

                <h3 class="tbk_title_h3">Información de Registros</h3>
                <table class="tbk_table_info">
                    <tr style="display: none !important;">
                        <td>
                            <div title="Informa si actualmente se guarda la información de cada compra mediante Webpay" class="label label-info">?</div> <strong>Estado de Registros: </strong>
                        </td>
                        <td class="tbk_table_td">
                            <?php
                            if ($this->tbk_data['lockfile']){
                                echo '<span id="action_txt" class="label label-success2">Registro activado</span>';
                            } else {
                                echo '<span id="action_txt" class="label label-warning">Registro desactivado</span>';
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td><div title="Carpeta en el servidor en donde se guardan los archivos con la informacón de cada compra mediante Webpay" class="label label-info">?</div> <strong>Directorio de Registros: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['log_dir']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Cantidad de archivos que guardan la información de cada compra mediante Webpay" class="label label-info">?</div> <strong>Cantidad de Registros en Directorio: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['logs_count']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Lista los archivos archivos que guardan la información de cada compra mediante Webpay" class="label label-info">?</div> <strong>Listado de Registros Disponibles: </strong></td>
                        <td class="tbk_table_td">
                            <ul style="font-size:0.8em;list-style: disc">
                            <?php
                                $logs_list = $this->tbk_data['logs_list'];
                                foreach ($logs_list as $index){
                                echo '<li>'.$index.'</li>';
                                }
                            ?>
                            </ul>
                        </td>
                    </tr>
                </table>

                <h3 class="tbk_title_h3">Últimos Registros</h3>
                <table class="tbk_table_info">
                    <tr>
                        <td><div title="Nombre del útimo archivo de registro creado" class="label label-info">?</div> <strong>Último Documento: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['log_file']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Peso del último archivo de registro creado" class="label label-info">?</div> <strong>Peso del Documento: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['log_weight']; ?></td>
                    </tr>
                    <tr>
                        <td><div title="Cantidad de líneas que posee el último archivo de registro creado" class="label label-info">?</div> <strong>Cantidad de Líneas: </strong></td>
                        <td class="tbk_table_td"><?php echo $this->tbk_data['log_regs_lines']; ?></td>
                    </tr>
                </table>

                <br>

                <pre>
                    <span style="font-size: 10px; font-family:monospace; display: block; background: white;width: fit-content;" >
                    <?php echo $this->tbk_data['logs']; ?>
                    </span>
                </pre>
            </fieldset>
        </div>
    </div>
</div>

<script type="text/javascript">

	jQuery().ready(function($){

        $(".check_conn").click(function() {

            $(".btn_status").hide();
            $(".check_conn").text("Verificando ...");
            $("#row_response_url").hide();
            $("#row_response_token").hide();
            $("#row_error_message").hide();
            $("#row_error_detail").hide();
            $("#row_response_status").hide();
            $(".error-content").empty();
            $(".error_detail_content").empty();
            $(".content_url").empty();
            $(".content_token").empty();

            var url = '<?php echo $this->tbk_data['url_request']; ?>';
            var params = {
                "type": "checkInit"
            };

            $.post(url, params, function(response) {

                $(".status-label").show();
                $(".check_conn").text("Verificar Conexión");
                $("#row_response_status").show();

                if(response.success) {
                    $(".status-label").removeClass("label-success2");
                    $(".status-label").removeClass("label-danger2");
                    if(response.msg.status.string == "OK") {
                        $(".status-label").text("OK");
                        $(".status-label").addClass("label-success2");
                        $(".content_url").append(response.msg.response.url);
                        $(".content_token").append('<pre>'+response.msg.response.token_ws+'</pre>');
                        $("#row_response_url").show();
                        $("#row_response_token").show();
                    } else {
                        $(".status-label").addClass("label-danger2");
                        $(".status-label").text("ERROR");
                        $("#row_error_message").show();
                        $("#row_error_detail").show();
                        $(".error-content").append(response.msg.response.error);
                        $(".error_detail_content").append('<pre><code>'+response.msg.response.detail+'</code></pre>');
                    }
                } else {
                    $(".status-label").removeClass("label-success2");
                    $(".status-label").removeClass("label-danger2");
                    $(".status-label").addClass("label-danger2");
                    $(".status-label").append("ERROR");
                    $(".error_detail_content").append('<pre><code>'+response.msg+'</code></pre>');
                    $("#row_error_message").show();
                    $("#row_error_detail").show();
                }
            },'json');
        });

        $('#btn-save-data-conf').click(function(evt) {
            var action_check = $('#action_check').is(':checked');
            var size = $('#size').val();
            var days = $('#days').val();
            var url = '<?php echo $this->tbk_data['url_call_log_handler']; ?>';
            var params = {
                'action_check': action_check,
                'size': size,
                'days': days
            };
            $.post(url, params, function(response) {
                if (action_check){
                    $('#action_txt').empty().text('Registro activado');
                    $('#action_txt').addClass('label-success2');
                    $('#action_txt').removeClass('label-warning');
                } else {
                    $('#action_txt').empty().text('Registro desactivado');
                    $('#action_txt').addClass('label-warning');
                    $('#action_txt').removeClass('label-success2');
                }
            },'json');
            evt.preventDefault();
        });
	});

    function showModal() {
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal',
                'mage/tabs',
            ],
            function($, modal, tabs, url) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    buttons: [{
                        text: $.mage.__('Cerrar'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#popup-modal'));
                $('#popup-modal').modal('openModal');
                $("#row_response_url").hide();
                $("#row_response_token").hide();
                $("#row_error_message").hide();
                $("#row_error_detail").hide();
                $("#row_response_status").hide();
            },
            function($, tabs) {
                $("#horizontal_tabs").tabs();
            }
        );
    }

</script>
